# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cd7ddbf8c4248311cd677c5f11e183ca157fbd02fb0e8b370d644d11b6fda7119d38f33eb01df61a00a879a05f18947802f4cef211bbf8da17e7b2ddb7b985a

test:
  secret_key_base: 6ddaeddd68ded50815076acd4371c155203f9f159560d09717199a590c0ebfe5751d6e06ca76ca41572ab0c3e0146607e1549bc6989d8d24d167a23b24f06dae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
